In [1]:
import numpy as np

In [2]:
np.array([4,2,5,2,5])

array([4, 2, 5, 2, 5])

In [3]:
import numpy as np
np.array([4,2,5,2,5])
np.arange(32)

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

To jest pierwszy **notebook** oparty na mechanizmie <span style="color:red;font-size:16pt;font-family:Impact;">Jupyter Notebook</span>

In [4]:
n = np.arange(12)
print(n)
print(type(n))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [5]:
w = np.array([[1,2,3,4],[5,6,7,8],[14,56,78,99]])
w

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [14, 56, 78, 99]])

In [7]:
w[0][2]

3

In [8]:
w[0,2]

3

In [9]:
zw = list([[3,6],[7,9]])
zw

[[3, 6], [7, 9]]

In [10]:
zw[0][0]

3

In [12]:
w[w<5]

array([1, 2, 3, 4])

In [13]:
pc = (w>=5)
w[pc]

array([ 5, 6, 7, 8, 14, 56, 78, 99])

In [14]:
lg = (w%2==0)
w[lg]

array([ 2, 4, 6, 8, 14, 56, 78])

In [20]:
cv = w[(w>2)&(w<=21)]
cv

array([ 3, 4, 5, 6, 7, 8, 14])

In [21]:
sv = w[(w<8) | (w>35)]
sv

array([ 1, 2, 3, 4, 5, 6, 7, 56, 78, 99])

In [22]:
l1 = [4,5,3]
l2 = [324,57,37]
lw = l1+l2
lw
#opertor + w przypadku obiektu list dokonuje konkatenacji

[4, 5, 3, 324, 57, 37]

In [23]:
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [24]:
print(dane+one)

[2 4 9]


In [25]:
print(dane-one)

[0 2 7]


In [26]:
print(dane*tw)

[ 2  6 24]


In [27]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [28]:
print(dane*1.85)

[ 1.85  5.55 14.8 ]


In [29]:
m1 = np.array([[4,8,11],[67,101,3],[1,1,77]])
m2 = np.array([[488,9,3],[23,89,3],[2,4,11]])
wynik = (m1+m2)*m1
wynik

array([[ 1968, 136, 154],
 [ 6030, 19190, 18],
 [ 3, 5, 6776]])

In [30]:
print(f'wartość minimum: {wynik.min()}')
print(f'wartość maximum: {wynik.max()}')
print(f'wartość średnia: {wynik.mean()}')
print(f'wartość std: {wynik.std()}')

wartość minimum: 3
wartość maximum: 19190
wartość średnia: 3808.8888888888887
wartość std: 5998.870809381906


In [34]:
#tensor
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
#tablica 5D
arr5 = np.arange(240).reshape((2,2,4,5,3))
arr5

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1