In [1]:
import numpy as np

In [2]:
np.array([4,2,5,2,5])

array([4, 2, 5, 2, 5])

In [3]:
import numpy as np
np.array([4,2,5,2,5])
np.arange(32)

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

To jest pierwszy **notebook** oparty na mechanizmie <span style="color:red;font-size:16pt;font-family:Impact;">Jupyter Notebook</span>

In [4]:
n = np.arange(12)
print(n)
print(type(n))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [5]:
w = np.array([[1,2,3,4],[5,6,7,8],[14,56,78,99]])
w

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [14, 56, 78, 99]])

In [7]:
w[0][2]

3

In [8]:
w[0,2]

3

In [9]:
zw = list([[3,6],[7,9]])
zw

[[3, 6], [7, 9]]

In [10]:
zw[0][0]

3

In [12]:
w[w<5]

array([1, 2, 3, 4])

In [13]:
pc = (w>=5)
w[pc]

array([ 5, 6, 7, 8, 14, 56, 78, 99])

In [14]:
lg = (w%2==0)
w[lg]

array([ 2, 4, 6, 8, 14, 56, 78])

In [20]:
cv = w[(w>2)&(w<=21)]
cv

array([ 3, 4, 5, 6, 7, 8, 14])

In [21]:
sv = w[(w<8) | (w>35)]
sv

array([ 1, 2, 3, 4, 5, 6, 7, 56, 78, 99])